### PR TITLE
Wrote LIC5 function & made tests work with Travis & wrote test for LIC5

### LINKED ISSUE #6: Write function checking LIC 5

### PR DESCRIPTION
**Pull request by evkade**
Resolves #6

### CODE REVIEW

**Comment by evkade** [comment]
Maybe this should not be merged because not tests have been written for it yet.

**Comment by ayubatif** [comment]
yes, only merge after Travis checks are passed and the unit tests (correctness and test inputs) are passed. It is bad practice to push untested code to main since everything on main is assumed to work.

**Comment by ayubatif** [comment]
when you compare two doubles, use the doublecompare(double a, double b) function instead of directly comparing.

**Review by ayubatif — APPROVED** [review]
LGTM, change title to fit and squash

**Pull request merged**
